### ISSUE TITLE
Include additional fields when submitting to LeadiD

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-leadid#12]
The additional Data fields are required as follows:
* loan_type
* loan_amount
* credit_rating
* property_type
* prop_address
* prop_city
* prop_state
* prop_zip
* primary_use

Please add these to the list of pipe-delimited fields in `data` that we send to LeadiD. When this is done, we'll need to coordinate with LeadiD to send a test lead.

**Comment by alexj** [comment]
Chris, could you knock this out or work with Lynda or Jonathan to make these changes?

**Comment by jgrayson676** [comment]
Which of our fields should be used for `loan_type` (and `loan_amount`), `loan.type` or `mortgage.loan.type`? Or whichever is available?

**Comment by alexj** [comment]
It should send over whichever one is available. Thanks.

**Comment by alexkwolfe** [comment]
I wonder what property info they want. Is that the consumer's current property or the property being financed? In mortgage flows we have both.

**Comment by alexj** [comment]
Good question. My expectation is that they care about the property to be purchased, but I'll ask Hansen to verify.

**Comment by alexj** [comment]
Verified - all property values are for the property to be purchased.
